[tool.poetry]
name = "usb_kvm_client"
version = "1.0.0.0"
description = "simple USB KVM client"
authors = ["wevsty <ty@wevs.org>"]
package-mode = false

[tool.black]
line-length = 80
target-version = ["py313"]
include = "\\.pyi?$"
extend-exclude = """
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/.idea/.*
  | /build/.*
  | /ui_resource/.*
  | /data/.*
)
"""

[tool.poetry.dependencies]
python = "<3.14,>=3.12"
pyyaml = "^6.0.2"
loguru = "^0.7.2"
pywin32 = { version = ">=308", markers = "platform_system == 'Windows'" }
pyside6-addons = "^6.8.2"
pyside6-essentials = "^6.8.2"
pyside6 = "^6.8.2"
pywinhook = { version = "^1.6.2", markers = "platform_system == 'Windows'" }
pyserial = "^3.5"
ch9329 = "^1.2.7"
nuitka = "^2.6.5"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
isort = "^5.13.2"
flake8-bugbear = "^24.10.31"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
